import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys =>
      {
        'en_US': {
          "New Request": "New Request",
          "Name": "Name",
          "Phone Number": "Phone Number",
          "Type Of Event": "Type Of Event",
          "Owner Of Event": "Owner Of Event",
          "Hour": "Hour",
          "Date": "Date",
          "Address": "Address",
          "Type of Building": "Type of Building",
          "Float": "Float",
          "Please Enter Float": "Please Enter Float",
          "Please Enter Type of Building": "Please Enter Type of Building",
          "Please Enter Address": "Please Enter Address",
          "Please Enter Date": "Please Enter Date",
          "Please Enter Hour": "Please Enter Hour",
          "Please Enter Owner Of Event": "Please Enter Owner Of Event",
          "Please Enter Type Of Event": "Please Enter Type Of Event",
          "Please Enter Phone Number": "Please Enter Phone Number",
          "Please Enter Name": "Please Enter Name",
          "Next": "Next",
          "Complete Request": "Complete Request",
          "Notes": "Notes",
          "Add Item": "Add Item",
          "Add Special Desgin": "Add Special Desgin",
          "Upload Images": "Upload Images",
          "Deposit": "Deposit",
          "Bank": "Bank",
          "Please select an item": "Please select an item",
          "Receiving": "Receiving",
          "Select Catalog": "Select Catalog",
          "Please select a catalog": "Please select a catalog",
          "Select Sub-Category": "Select Sub-Category",
          "Please select a sub-category": "Please select a sub-category",
          "Select Sub-Sub-Category": "Select Sub-Sub-Category",
          "Please select a sub-sub-category": "Please select a sub-sub-category",
          "Select Final Item": "Select Final Item",
          "Image": "Image",
          "Price": "Price",
          "Action": "Action",
          "Staff": "Staff",
          "Select User": "Select User",
          "Please select an User": "Please select an User",
          "Select Type": "Select Type",
          "Please select a type": "Please select a type",
          "Add Staff": "Add Staff",
          "No Staff found.": "No Staff found.",
          "Edit": "Edit",
          "Email": "Email",
          "Type": "Type",
          "Edit Employee": "Edit Employee",
          "Update Type": "Update Type",
          "Delete Employee": "Delete Employee",
          "Sign in": "Sign in",
          "Password": "Password",
          "enter your password": "enter your password",
          "Remember Me": "Remember Me",
          "Forgot Password?": "Forgot Password?",
          "Google": "Google",
          "Please Enter Your Password": "Please Enter Your Password",
          "Please Enter Your Email": "Please Enter Your Email",
          "Login": "Login",
          "Don't have an Account? ": "Don't have an Account? ",
          "Sign up": "Sign up",
          "UserName": "UserName",
          "Phone no": "Phone no",
          "Confirm Password": "Confirm Password",
          "confirm your password": "confirm your password",
          "Please Enter Your Phone": "Please Enter Your Phone",
          "Please Enter Your Name": "Please Enter Your Name",
          "Password Not Match": "Password Not Match",
          "Please Choose Your Image Profile": "Please Choose Your Image Profile",
          "Create Account": "Create Account",
          "Already have an Account? ": "Already have an Account? ",
          "Image selection simulated!": "Image selection simulated!",
          "Welcome": "Welcome",
          "Your journey to a better life starts here.": "We wish you days filled with joy\n and celebrations.",
          "Continue": "Continue",
          "Forget Password": "Forget Password",
          "Send Email": "Send Email",
          "Please select action": "Please select action",
          "Link": "Link",
          "Url link": "Url link",
          "Please Upload Secound Image": "Please Upload Secound Image",
          "Please Enter Url": "Please Enter Url",
          "Please Upload Image": "Please Upload Image",
          "Add New Banner": "Add New Banner",
          "Banners": "Banners",
          "Edit Banner": "Edit Banner",
          "Update Banner": "Update Banner",
          "Delete Banner": "Delete Banner",
          "No Image Selection": "No Image Selection",
          "No items found.": "No items found.",
          "Calender": "Calender",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "You Don't Have Any Task": "You Don't Have Any Task",
          "Catalog": "Catalog",
          "Search Item": "Search Item",
          "Name OF Item": "Name OF Item",
          "Description": "Description",
          "Description OF Item": "Description OF Item",
          "Price OF Item": "Price OF Item",
          "Add New Item": "Add New Item",
          "Add New Category": "Add New Category",
          "Add New SubCategory": "Add New SubCategory",
          "Please Complete Data": "Please Complete Data",
          "Add New SubSubCategory": "Add New SubSubCategory",
          "Update": "Update",
          "Please Add Name": "Please Add Name",
          "Edit Item": "Edit Item",
          "Save Edit Item": "Save Edit Item",
          "Delete Item": "Delete Item",
          "Chat": "Chat",
          "Good Morning,": "Good Morning,",
          "Top Catalog Items": "Top Catalog Items",
          "Show All": "Show All",
          "My Requests": "My Requests",
          "Home": "Home",
          "Add": "Add",
          "Profile": "Profile",
          "All Request": "All Request",
          "Failed to load image": "Failed to load image",
          "Good Morning": "Good Morning",
          "Select date": "Select date",
          "Access": "Access",
          "Requset List": "Requset List",
          "View List": "View List",
          "View Staff": "View Staff",
          "Show Catalog": "Show Catalog",
          "Order": "Order",
          "On-hold": "On-hold",
          "Show Banners": "Show Banners",
          "Reports": "Reports",
          "Show Reports": "Show Reports",
          "InBox": "InBox",
          "Show InBox Mail": "Show InBox Mail",
          "Offers": "Offers",
          "Create Offer": "Create Offer",
          "Show All tasks": "Show All tasks",
          "Title": "Title",
          "Body": "Body",
          "Please Enter Body": "Please Enter Body",
          "Please Enter Title": "Please Enter Title",
          "Add New InBox": "Add New InBox",
          "No InBox found.": "No InBox found.",
          "ID": "ID",
          "ID OF Item": "ID OF Item",
          "Price Buy OF Item": "Price Buy OF Item",
          "Count": "Count",
          "Count OF Item": "Count OF Item",
          "Show Price": "Show Price",
          "Please Enter Count": "Please Enter Count",
          "Please Enter Price Of Buy": "Please Enter Price Of Buy",
          "Please Enter Price": "Please Enter Price",
          "Please Enter ID": "Please Enter ID",
          "Picture": "Picture",
          "Total Price": "Total Price",
          "Items": "Items",
          "Choose the language": "Choose the language",
          "English": "English",
          "Click here to Choose": "Click here to Choose",
          "Arabic": "Arabic",
          "No Notification found.": "No Notification found.",
          "Notification History": "Notification History",
          "Create Offer Price": "Create Offer Price",
          "Company Name": "Company Name",
          "Delivry Price": "Delivry Price",
          "Size": "Size",
          "Client & Request Details": "Client & Request Details",
          "Request Date": "Request Date",
          "Order Number": "Order Number",
          "Event & Location": "Event & Location",
          "Event Type": "Event Type",
          "Event Owner": "Event Owner",
          "Payment Summary": "Payment Summary",
          "Payment Method": "Payment Method",
          "Remaining Fees": "Remaining Fees",
          "Create": "Create",
          "Assign Staff Members": "Assign Staff Members",
          "Coordinator:": "Coordinator:",
          "Designer:": "Designer:",
          "Driver:": "Driver:",
          "Vendor:": "Vendor:",
          "Requested Items": "Requested Items",
          "Tax": "Tax",
          "Total": "Total",
          "Design Attached": "Design Attached",
          "No Design Provided": "No Design Provided",
          "Special Design Status": "Special Design Status",
          "Status:": "Status:",
          "Please Select All Staff": "Please Select All Staff",
          "Save Edit": "Save Edit",
          "Edit Staff Members": "Edit Staff Members",
          "Order Details": "Order Details",
          "Coordinator": "Coordinator",
          "Designer": "Designer",
          "Driver": "Driver",
          "Vendor": "Vendor",
          "createby": "createby",
          "Show Tasks": "Show Tasks",
          "Edit Price": "Edit Price",
          "Save": "Save",
          "Tasks": "Tasks",
          "Employee": "Employee",
          "Compelete": "Compelete",
          "Receipt from store": "Receipt from store",
          "Shipped": "Shipped",
          "Start moving": "Start moving",
          "Delivered": "Delivered",
          "installation": "installation",
          "Receipt from the customer": "Receipt from the customer",
          "Finish": "Finish",
          "Update Profile": "Update Profile",
          "Enter New Password": "Enter New Password",
          "Confirm New Password": "Confirm New Password",
          "Passwords Not match": "Passwords Not match",
          "Please Confirm New Password": "Please Confirm New Password",
          "Please Enter New Password": "Please Enter New Password",
          "Update Your Password": "Update Your Password",
          "Full Name": "Full Name",
          "Update Password": "Update Password",
          "Error": "Error",
          "OK": "OK",
          "Date": "Date",
          "Accept": "Accept",
          "Reject": "Reject",
          "Jop Order": "Jop Order",
          "Request Details": "Request Details",
          "Phone Number": "Phone Number",
          "Hour": "Hour",
          "type of building": "type of building",
          "No Special Desgin": "No Special Desgin",
          "Special Desgin": "Special Desgin",
          "Branch": "Branch",
          "BankType": "BankType",
          "Fees": "Fees",
          "Jop Order": "Jop Order",
          "All Request": "All Request",
          "Message": "Message",
          "Comment": "Comment",
          "Enter Your Comment": "Enter Your Comment",
          "Please Enter Comment": "Please Enter Comment",
          "Add Comment": "Add Comment",
          "No Comments": "No Comments",
          "Special Design Status": "Special Design Status",
          "Design Task": "Design Task",
          "Finish Task": "Finish Task",
          "Current Opretian": "Current Opretian",
          "Desgin": "Desgin",
          "Due date": "Due date",
          "Please select an item and quantity.": "Please select an item and quantity.",
          "Vendor Task": "Vendor Task",
          "Choose an item": "Choose an item",
          "Quantity:": "Quantity:",
          "Enter quantity": "Enter quantity",
          "No items added yet.": "No items added yet.",
          "Quantity": "Quantity",
          "Item": "Item",
          "No Action": "No Action",
          "All Task": "All Task",
          "Add New Staff":"Add New Staff",
          "Language":"Language",
          "Terms of Use":"Terms of Use",
          "Privacy Policy":"Privacy Policy",
          "Remove Account":"Remove Account",
          "Logout":"Logout",
          "SAT":"SAT",
          "MON":"MON",
          "WED":"WED",
          "THU":"THU",
          "FRI":"FRI",
          "SUN":"SUN",
          "TUE":"TUE",
          "Admin":"Admin",
          "vendor":"vendor",
          "driver":"driver",
          "designer":"designer",
          "coordinator":"coordinator",
          "Price Buy":"Price Buy",
          "January":"January",
          "February":"February",
          "March":"March",
          "April":"April",
          "May":"May",
          "June":"June",
          "July":"July",
          "August":"August",
          "September":"September",
          "October":"October",
          "November":"November",
          "December":"December",
          "Tasks for":"Tasks for",
          "The Store":"The Store",
          "User":"User",
          "All":"All",
          "InReview":"InReview",
          "Progress":"Progress",
          "Client":"Client",
          "Report":"Report",
          "remove":"remove",
          "add":"add",
          "Time":"Time",
          "client":"client",
          "Phone":"Phone",
          "Type Of Building":"Type Of Building",
          "Created By":"Created By",
          "Status":"Status",
          "Submit":"Submit",
          "Please insert image":"Please insert image",
          "Please Enter Price":"Please Enter Price",
          "Please Enter Description":"Please Enter Description",
          "Please Select Bank":"Please Select Bank",
          "Please Select Branch":"Please Select Branch",
          "Please Select Items":"Please Select Items",
          "Choose Action":"Choose Action",
          "Add New Sub":"Add New Sub",
          "Please Choose Action":"Please Choose Action",
          "Submit":"Submit",
          "Select Role":"Select Role",
          "Search user by name or email":"Search user by name or email",
          "Select Time":"Select Time",
          "Select Date":"Select Date",
          "Manual":"Manual",
          "Quantity":"Quantity",
          "Select Store Item":"Select Store Item",
          "Add Store Item":"Add Store Item",
          "Store":"Store",
          "Item Name":"Item Name",
          "Price":"Price",
          "Select Image":"Select Image",
          "Add Manual Item":"Add Manual Item",
          "Add Special Design":"Add Special Design",
          "Perview":"Perview"
        },
        'ar_DZ': {
          "Perview":"معاينة واجهة المستخدم",
          "Add Special Design":"إضافة تصميم خاص",
          "Add Manual Item":"إضافة عنصر يدوي",
          "Select Image":"حدد الصورة",
          "Item Name":"اسم العنصر",
          "Store":"المخزن",
          "Add Store Item":"إضافة عنصر المتجر",
          "Select Store Item":"حدد عنصر المتجر",
          "Quantity":"كمية",
          "Manual":"يدوي",
          "Select Date":"حدد التاريخ",
          "Select Time":"حدد الوقت",
          "Search user by name or email":"البحث عن المستخدم حسب الاسم أو البريد الإلكتروني",
          "Select Role":"حدد الدور",
          "Submit":"تسليم",
          "Please Choose Action":"الرجاء اختيار الإجراء",
          "Add New Sub":"إضافة فرعية جديدة",
          "Choose Action":"اختر الإجراء",
          "Please Select Items":"الرجاء تحديد العناصر",
          "Please Select Branch":"الرجاء اختيار الفرع",
          "Please Select Bank":"الرجاء اختيار البنك",
          "Please Enter Description":"برجاء ادخال الوصف",
          "Please insert image":"برجاء ادخال صورة",
          "Submit":"تسليم",
          "Status":"حالة",
          "Created By":"تم الإنشاء بواسطة",
          "Type Of Building":"نوع المبنى",
          "Phone":"هاتف",
          "client":"عميل",
          "Time":"وقت",
          "remove":"خروج",
          "add":"اضافة",
          "Report":"تقارير",
          "Client":"عميل",
          "All":"الكل",
          "InReview":"تحت المراجعة",
          "Progress":"تحت التنفيذ",
          "The Store":"المخزن",
          "User":"المستخدم",
          "Tasks for":"المهام ل",
          "January":"يناير",
          "February":"فبراير",
          "March":"مارس",
          "April":"أبريل",
          "May":"مايو",
          "June":"يونيو",
          "July":"يوليو",
          "August":"أغسطس",
          "September":"سبتمبر",
          "October":"أكتوبر",
          "November":"نوفمبر",
          "December":"ديسمبر",
          "Price Buy":"سعر الشراء",
          "Admin":"مسؤول",
          "vendor":"مدير مخزن",
          "driver":"سائق",
          "designer":"مصمم",
          "coordinator":"منظم",
          "TUE":"الثلاثاء",
          "SUN":"الاحد",
          "SAT":"السبت",
          "MON":"الاثنين",
          "WED":"الاربعاء",
          "THU":"الخميس",
          "FRI":"الجمعة",
          "Error": "خطأ",
          "OK": "موافق",
          "Accept": "قبول",
          "Reject": "رفض",
          "Jop Order": "طلب عمل",
          "Message": "رسالة",
          "Comment": "تعليق",
          "Enter Your Comment": "أدخل تعليقك",
          "Please Enter Comment": "يرجى إدخال تعليق",
          "Add Comment": "إضافة تعليق",
          "No Comments": "لا توجد تعليقات",
          "Design Task": "مهمة التصميم",
          "Finish Task": "إنهاء المهمة",
          "Current Opretian": "العملية الحالية",
          "Desgin": "تصميم",
          "Due date": "تاريخ الاستحقاق",
          "Please select an item and quantity.": "يرجى اختيار عنصر والكمية.",
          "Vendor Task": "مهمة البائع",
          "Choose an item": "اختر عنصرًا",
          "Quantity:": "الكمية:",
          "Enter quantity": "أدخل الكمية",
          "No items added yet.": "لم يتم إضافة عناصر بعد.",
          "Quantity": "الكمية",
          "Item": "عنصر",
          "No Action": "لا يوجد إجراء",
          "All Task": "جميع المهام",
          "Add New Staff": "إضافة موظف جديد",
          "Language": "اللغة",
          "Terms of Use": "شروط الاستخدام",
          "Privacy Policy": "سياسة الخصوصية",
          "Remove Account": "حذف الحساب",
          "Logout": "تسجيل الخروج",
          "New Request": "إضافة طلبية جديدة",
          "Name": "الاسم",
          "Phone Number": "رقم الهاتف",
          "Type Of Event": "نوع المناسبة",
          "Owner Of Event": "صاحب المناسبة",
          "Hour": "الساعة",
          "Date": "التاريخ",
          "Address": "العنوان",
          "Type of Building": "نوع المبنى",
          "Float": "عدد الطوابق",
          "Please Enter Float": "الرجاء إدخال عدد الطوابق",
          "Please Enter Type of Building": "الرجاء إدخال نوع المبنى",
          "Please Enter Address": "الرجاء إدخال العنوان",
          "Please Enter Date": "الرجاء إدخال التاريخ",
          "Please Enter Hour": "الرجاء إدخال الساعة",
          "Please Enter Owner Of Event": "الرجاء إدخال اسم صاحب المناسبة",
          "Please Enter Type Of Event": "الرجاء إدخال نوع المناسبة",
          "Please Enter Phone Number": "الرجاء إدخال رقم الهاتف",
          "Please Enter Name": "الرجاء إدخال الاسم",
          "Next": "التالي",
          "Complete Request": "إكمال الطلب",
          "Notes": "ملاحظات",
          "Add Item": "إضافة عنصر",
          "Add Special Desgin": "إضافة تصميم خاص",
          "Upload Images": "رفع الصور",
          "Deposit": "دفعة مقدمة",
          "Bank": "البنك",
          "Please select an item": "يرجى اختيار عنصر",
          "Receiving": "الاستلام",
          "Select Catalog": "اختر الكتالوج",
          "Please select a catalog": "يرجى اختيار كتالوج",
          "Select Sub-Category": "اختر الفئة الفرعية",
          "Please select a sub-category": "يرجى اختيار فئة فرعية",
          "Select Sub-Sub-Category": "اختر الفئة الفرعية الثانية",
          "Please select a sub-sub-category": "يرجى اختيار فئة فرعية ثانية",
          "Select Final Item": "اختر العنصر النهائي",
          "Image": "صورة",
          "Price": "السعر",
          "Action": "الإجراء",
          "Staff": "الموظفين",
          "Select User": "اختر المستخدم",
          "Please select an User": "يرجى اختيار مستخدم",
          "Select Type": "اختر النوع",
          "Please select a type": "يرجى اختيار النوع",
          "Add Staff": "إضافة موظف",
          "No Staff found.": "لم يتم العثور على موظفين.",
          "Edit": "تعديل",
          "Email": "البريد الإلكتروني",
          "Type": "النوع",
          "Edit Employee": "تعديل الموظف",
          "Update Type": "تحديث النوع",
          "Delete Employee": "حذف الموظف",
          "Sign in": "تسجيل الدخول",
          "Password": "كلمة المرور",
          "enter your password": "أدخل كلمة المرور",
          "Remember Me": "تذكرني",
          "Forgot Password?": "هل نسيت كلمة المرور؟",
          "Google": "جوجل",
          "Please Enter Your Password": "الرجاء إدخال كلمة المرور",
          "Please Enter Your Email": "الرجاء إدخال البريد الإلكتروني",
          "Login": "تسجيل الدخول",
          "Don't have an Account? ": "ليس لديك حساب؟ ",
          "Sign up": "إنشاء حساب",
          "UserName": "اسم المستخدم",
          "Phone no": "رقم الهاتف",
          "Confirm Password": "تأكيد كلمة المرور",
          "confirm your password": "أكد كلمة المرور",
          "Please Enter Your Phone": "الرجاء إدخال رقم الهاتف",
          "Please Enter Your Name": "الرجاء إدخال الاسم",
          "Password Not Match": "كلمتا المرور غير متطابقتين",
          "Please Choose Your Image Profile": "يرجى اختيار صورة الملف الشخصي",
          "Create Account": "إنشاء حساب",
          "Already have an Account? ": "لديك حساب بالفعل؟ ",
          "Image selection simulated!": "تم محاكاة اختيار الصورة!",
          "Welcome": "مرحبًا",
          "Your journey to a better life starts here.": " نتمني لك اياما مليئة بالفرح والاحتفالات.",
          "Continue": "استمرار",
          "Forget Password": "نسيت كلمة المرور",
          "Send Email": "إرسال البريد الإلكتروني",
          "Please select action": "يرجى اختيار إجراء",
          "Link": "رابط",
          "Url link": "رابط إلكتروني",
          "Please Upload Secound Image": "يرجى تحميل الصورة الثانية",
          "Please Enter Url": "يرجى إدخال الرابط",
          "Please Upload Image": "يرجى تحميل الصورة",
          "Add New Banner": "إضافة لافتة جديدة",
          "Banners": "لافتات",
          "Edit Banner": "تعديل لافتة",
          "Update Banner": "تحديث لافتة",
          "Delete Banner": "حذف لافتة",
          "No Image Selection": "لا يوجد اختيار صورة",
          "No items found.": "لم يتم العثور على عناصر.",
          "Calender": "التقويم",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "الخميس",
          "Friday": "الجمعة",
          "Saturday": "السبت",
          "You Don't Have Any Task": "ليس لديك أي مهمة",
          "Catalog": "الكتالوج",
          "Search Item": "بحث عنصر",
          "Name OF Item": "اسم العنصر",
          "Description": "الوصف",
          "Description OF Item": "وصف العنصر",
          "Price OF Item": "سعر العنصر",
          "Add New Item": "إضافة عنصر جديد",
          "Add New Category": "إضافة فئة جديدة",
          "Add New SubCategory": "إضافة فئة فرعية جديدة",
          "Please Complete Data": "الرجاء إكمال البيانات",
          "Add New SubSubCategory": "إضافة فئة فرعية ثانية",
          "Update": "تحديث",
          "Please Add Name": "الرجاء إضافة الاسم",
          "Edit Item": "تعديل العنصر",
          "Save Edit Item": "حفظ تعديل العنصر",
          "Delete Item": "حذف العنصر",
          "Chat": "الدردشة",
          "Good Morning,": "صباح الخير،",
          "Top Catalog Items": "أفضل عناصر الكتالوج",
          "Show All": "عرض الكل",
          "My Requests": "طلباتي",
          "Home": "الرئيسية",
          "Add": "إضافة",
          "Profile": "الملف الشخصي",
          "All Request": "جميع الطلبات",
          "Failed to load image": "فشل في تحميل الصورة",
          "Good Morning": "صباح الخير",
          "Select date": "اختر التاريخ",
          "Access": "الوصول",
          "Requset List": "قائمة الطلبات",
          "View List": "عرض القائمة",
          "View Staff": "عرض الموظفين",
          "Show Catalog": "عرض الكتالوج",
          "Order": "اوامر التشغيل",
          "On-hold": "قيد التشغيل",
          "Show Banners": "عرض اللافتات",
          "Reports": "التقارير",
          "Show Reports": "عرض التقارير",
          "InBox": "صندوق الوارد",
          "Show InBox Mail": "عرض بريد الوارد",
          "Offers": "عرض سعر",
          "Create Job Order":"انشاء امر التشغيل",
          "Client Name":"اسم العميل",
          "Client Phone":"رقم هاتف العميل",
          "Create Offer": "إنشاء عرض",
          "Show All tasks": "عرض كل المهام",
          "Title": "العنوان",
          "Body": "المحتوى",
          "Please Enter Body": "الرجاء إدخال المحتوى",
          "Please Enter Title": "الرجاء إدخال العنوان",
          "Add New InBox": "إضافة بريد جديد",
          "No InBox found.": "لم يتم العثور على بريد.",
          "ID": "معرّف",
          "ID OF Item": "معرّف العنصر",
          "Price Buy OF Item": "سعر شراء العنصر",
          "Count": "الكمية",
          "Count OF Item": "كمية العنصر",
          "Show Price": "عرض السعر",
          "Please Enter Count": "الرجاء إدخال الكمية",
          "Please Enter Price Of Buy": "الرجاء إدخال سعر الشراء",
          "Please Enter Price": "الرجاء إدخال السعر",
          "Please Enter ID": "الرجاء إدخال المعرّف",
          "Picture": "صورة",
          "Total Price": "السعر الإجمالي",
          "Items": "عناصر",
          "Choose the language": "اختر اللغة",
          "English": "الإنجليزية",
          "Click here to Choose": "اضغط هنا للاختيار",
          "Arabic": "العربية",
          "No Notification found.": "لم يتم العثور على إشعار.",
          "Notification History": "تاريخ الإشعارات",
          "Create Offer Price": "إنشاء سعر العرض",
          "Company Name": "اسم الشركة",
          "Delivry Price": "سعر التوصيل",
          "Size": "الحجم",
          "Client & Request Details": "تفاصيل العميل والطلب",
          "Request Date": "تاريخ الطلب",
          "Order Number": "رقم الطلب",
          "Event & Location": "المناسبة والموقع",
          "Event Type": "نوع المناسبة",
          "Event Owner": "مالك المناسبة",
          "Payment Summary": "ملخص الدفع",
          "Payment Method": "طريقة الدفع",
          "Remaining Fees": "الرسوم المتبقية",
          "Create": "إنشاء",
          "Assign Staff Members": "تعيين موظفين",
          "Coordinator:": "المنسق:",
          "Designer:": "المصمم:",
          "Driver:": "السائق:",
          "Vendor:": "البائع:",
          "Requested Items": "العناصر المطلوبة",
          "Tax": "الضريبة",
          "Total": "الإجمالي",
          "Design Attached": "تصميم مرفق",
          "No Design Provided": "لم يتم توفير تصميم",
          "Special Design Status": "حالة التصميم الخاص",
          "Status:": "الحالة:",
          "Please Select All Staff": "يرجى اختيار جميع الموظفين",
          "Save Edit": "حفظ التعديل",
          "Edit Staff Members": "تعديل الموظفين",
          "Order Details": "تفاصيل الطلب",
          "Coordinator": "المنسق",
          "Designer": "المصمم",
          "Driver": "السائق",
          "Vendor": "البائع",
          "createby": "أنشئ بواسطة",
          "Show Tasks": "عرض المهام",
          "Edit Price": "تعديل السعر",
          "Save": "حفظ",
          "Tasks": "المهام",
          "Employee": "الموظف",
          "Compelete": "اكتمل",
          "Receipt from store": "إيصال من المتجر",
          "Shipped": "تم الشحن",
          "Start moving": "بدء النقل",
          "Delivered": "تم التوصيل",
          "installation": "تركيب",
          "Receipt from the customer": "إيصال من العميل",
          "Finish": "إنهاء",
          "Update Profile": "تحديث الملف الشخصي",
          "Enter New Password": "أدخل كلمة المرور الجديدة",
          "Confirm New Password": "تأكيد كلمة المرور الجديدة",
          "Passwords Not match": "كلمات المرور غير متطابقة",
          "Please Confirm New Password": "يرجى تأكيد كلمة المرور الجديدة",
          "Please Enter New Password": "يرجى إدخال كلمة المرور الجديدة",
          "Update Your Password": "تحديث كلمة المرور",
          "Full Name": "الاسم الكامل",
          "Update Password": "تحديث كلمة المرور"
        }
      };
  }
